### ISSUE TITLE
Confusing statement in Communication Between Origins section

### ISSUE THREAD

**Issue by sideshowbarker** [martinthomson/wpack-content#2]
https://martinthomson.github.io/wpack-content/draft-thomson-wpack-content-origin.html#section-5.6

> This means that communication is only possible if the frame in which the content is loaded by the origin attempting communication, or the content is known to that origin.

A “then [*something*]” expectation is created by the word *if* in the condition *if the frame in which the content is loaded by the origin attempting communication*, but there’s no “something” there.

Or maybe the word *if* is a typo, and some other word was intended there?

**Comment by martinthomson** [comment]
Thanks for reading.  This is clearly not my best work, but I think that the sentence is complete.

The "then [something]" consequence is "communication is only possible" with a condition being that the "frame is loaded by the origin attempting communication, or ...".

**Comment by sideshowbarker** [comment]
Sorry, I think I’m still failing to parse it. Lemme try some rewordings to see if I understand —

“This means that communication is only possible if the frame in which the content is *is* loaded by the origin attempting communication”

…that is, add an additional “is” there.

Or maybe this:

“This means that communication is only possible if the frame *containing* the content is loaded by the origin attempting communication”

**Comment by martinthomson** [comment]
Thanks, that helps a lot. I'll make the change you suggest.
